name: check
on: push
jobs:
  test:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
      - run: pip install pytest pytest-cov
      - run: pytest --cov=./
      - uses: codecov/codecov-action@v1
